name: deploy repo to azure static site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Generate hash + rename css
      run: |
        HASH=$(sha1sum resume.css | cut -c1-8)
        NEWFILE="resume.$HASH.css"

        cp resume.css $NEWFILE

        sed -i 's|href="resume.css"|href="'"$NEWFILE"'"|g' resume.html

    - name: Upload to azure blob with azcopy
      run: |
          azcopy sync "./" "https://${{ secrets.AZURE_STORAGE_ACCOUNT }}.blob.core.windows.net/\$web${{ secrets.AZURE_SAS_TOKEN }}" \
          --recursive
          
